### PR TITLE
fix: use './static' as public dir for vite

### LINKED ISSUE #158: The vite's public folder conflicts with the nuxt's static folder.
Using nuxt-vite, special public directory is under your project root. Assets in this directory will be served at root path /;  While using the command nuxt ,assets in the 'static' directory will be served at root path / ; So it is ambugious when we use nuxt-vite, we should use public as th root path / or the static folder as root path /?
### Versions

nuxt-vite: v0.1.1
nuxt: 2.15.7

### Reproduction
Now using the static as root path /, sometimes the images could be found ,sometime not;
**the logo image could be found, while the default.png couldn't just as below**
Below is my folder structure. 
image

image

image

### PR DESCRIPTION
**Pull request by antfu**
close #158

### CODE REVIEW

File: src/vite.ts [hunk 1]
```diff
@@ -56,6 +56,7 @@ async function bundle (nuxt: Nuxt, builder: any) {
           jsxFactory: 'h',
           jsxFragment: 'Fragment'
         },
+        publicDir: resolve(nuxt.options.rootDir, nuxt.options.dir.assets),
```
Comment (pi0) [inline src/vite.ts:59]: Nuxt 2's public dir is `static` not assets

File: src/vite.ts [hunk 2]
```diff
@@ -56,6 +56,7 @@ async function bundle (nuxt: Nuxt, builder: any) {
           jsxFactory: 'h',
           jsxFragment: 'Fragment'
         },
+        publicDir: resolve(nuxt.options.rootDir, nuxt.options.dir.static),
```
Comment (pi0) [inline src/vite.ts:59]: https://github.com/nuxt/nuxt.js/blob/40521d0a0d2b3f9308e0c2df033f21b3ede76c7e/packages/server/src/server.js#L93

```suggestion
        publicDir: resolve(nuxt.options.srcDir, nuxt.options.dir.static),
```
