### PR TITLE
fix!: change vite root to `rootDir` from `buildDir`

### LINKED ISSUE #181: Use app root for Vite instead of buildDir
Allows most of vite plugins work out-of-box.

### PR DESCRIPTION
**Pull request by antfu**
On top of #179

close #181

### CODE REVIEW

File: src/server.ts [hunk 1]
```diff
@@ -92,7 +92,7 @@ export async function buildServer (ctx: ViteBuildContext) {
     .replace('{{ APP }}', '<div id="__nuxt">{{ APP }}</div>')
     .replace(
       '</body>',
-      '<script type="module" src="/@vite/client"></script><script type="module" src="/client.js"></script></body>'
+      '<script type="module" src="/@vite/client"></script><script type="module" src="/_nuxt/client.js"></script></body>'
```
Comment (pi0) [inline src/server.ts:95]: Note for the future: We need to support router base and custom build dir (`nuxt.options.app.assetsPath` instead of hardcoding `/_nuxt)

**Review by pi0 — APPROVED** [review]

File: src/server.ts (hunk 1 above)
Comment (pi0) [reply src/server.ts:95]: Related https://github.com/nuxt/vite/issues/166
